# Generated by Django 4.1.7 on 2023-03-23 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
