# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todolist_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='add_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
