# Generated by Django 4.2.3 on 2023-07-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todolist_add_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListItem',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
