# Generated by Django 4.2.3 on 2023-07-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_todolist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='finished',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.listitem', verbose_name='Subitem of...'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='list_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
