# Generated by Django 4.2.3 on 2023-07-12 16:20

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_todolist_finished_alter_listitem_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.listitem', verbose_name='Subitem of...'),
        ),
    ]
